In [2]:
import numpy as np

0-D Arrays

In [9]:
arr = np.array(42)
print(arr)

42


1-D Arrays

In [10]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2-D Arrays

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1,2])

[[1 2 3]
 [4 5 6]]
6


3-D Arrays

In [20]:
arr = np.array([[[1,2,3],[3,4,5]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr[1,0,1])
print(arr[1,-1])

[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [4 5 6]]]
2
[4 5 6]


Number Of Dimensions - განზომილების რაოდენობა

In [13]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1, 2,3],[3,4,5]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [25]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:6:3]) #arr[from:to:step]

[2 5]


In [26]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [27]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [36]:
arr = np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [37]:
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [39]:
arr = np.array([1,2,3,4,5])
x= arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [40]:
arr = np.array([1, 2,3,4,5])
x = arr.view()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [41]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [46]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array: ', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array:  (1, 1, 1, 1, 4)


In [54]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
newarr2 = arr.reshape(2,3,2)
print(newarr)
print("===")
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
===
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [55]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [59]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [60]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [62]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [63]:
arr = np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


SEARCH

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])
x = np.where(arr<5)
print(x[0])

[0 1 2 3]


In [11]:
arr = np.array([8, 6,  7,  9])

x = np.searchsorted(arr, 8)

print(x)

3


In [12]:
arr = np.array([12,3,23,5,33,2])
x = [True, False, True, True,False,False]
newarr = arr[x]
print(newarr)

[12 23  5]


In [13]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
