In [1]:
import numpy as np

SIMPLE ARITHMETICS

In [21]:
arr1 = np.array([3,6,3,4,6,2,2])
arr2 = np.array([6,2,3,8,6,4,2])
arr3 = np.array([1,-5,-10,2,-10])
# პირველ მასივს დამატებული მეორე მასივი
addTwoArrays = np.add(arr1,arr2)

# პირველ მასივს გამოკლებული მეორე მასივი
substructTwoArrays = np.subtract(arr1,arr2)

# პირველი მასივი გამრავლებული მეორე მასივზე
multiplyTwoArrays = np.multiply(arr1,arr2)

# პირველი მასივი გაყოფილი მეორე მასივზე
divideTwoArrays = np.divide(arr1,arr2)

# პირველი მასივის რიცხვები ავახარისხოთ მეორე მასივის რიცხვევზე
powerTwoArrays = np.power(arr1,arr2)

# პოულობს ნაშთებს პირველი მასივის მეორე მასივზე გაყოფისას
modOfTwoArrays = np.mod(arr1,arr2)

# აბრუნებს ორ მასივს გაყოფილის დამრგვალებულ ციფრებს და ნაშთებს
divmodOfTwoArrays = np.divmod(arr1,arr2)

# აბრუნებს იგივე მასივს მოდულში
absoluteNumbersOfArray = np.absolute(arr3)

[ 1  5 10  2 10]


ROUNDING DECIMALS

In [28]:
# ამრგვალებს 0-თან ახლო ციფრზე, fix და trunc ერთნაირად მუშაობს
arr = np.trunc([-3.1666, 3.6667])
arr = np.fix([-3.1666, 3.6667])

In [33]:
# განსაზღვრავს თუ რამდენი ციფრი უნდა იყოს წერტილის შემდეგ და ამრგვალებს შესაბამისად
num = np.around(3.1666, 2)
# ამრგვალებს მასივის ელემენტებს უმცირესამდე
arr = np.floor([-3.1666,3.6667])
# ამრგვალებს მასივის ელემენტებს უდიდესამდე
arr = np.ceil([-3.1666,3.6667])

[-3.  4.]


SUMMATIONS

In [43]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 = np.array([1,2,3])
# აკეთებს სამი მასივის ელემენტების შეჩამებას 
sumOfEachElems = np.sum([arr1,arr2,arr3])
# აკეთებს თითოეულ მასივის ელემენტების შეჯამებას მათივე მასივში
sumOfEachArrElems = np.sum([arr1,arr2,arr3],axis=1)
# ამატებს მასივის ელემენტებს ერთმანეთის მიყოლებით
cumSum = np.cumsum(arr1)


[1 3 6]


PRODUCTS

In [47]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

# ამრავლებს თითოეულ ელემენტს ერთმანეთზე
onlyOneArr = np.prod(arr1)

# ამრავლებს ორი მასივის თითოეულ ელემენტებს ერთმანეთზე
twoArrays = np.prod([arr1,arr2])

# ამრავლებს თითეული მასივის ელემენტებს და აბრუნებს თითოეული მასივის შედეგს
eachArrays = np.prod([arr1,arr2],axis=1)

# ამრავლებს ელემენტებს ერთმანეთზე მიყოლებით
cumProd = np.cumprod(arr1)

[ 1  2  6 24]


DIFFERENCES

In [49]:
arr= np.array([10,15,25,5])
# პოულობს რიცხვს თუ რამდენით იზრდება
newArr=np.diff(arr)

# ERROR IN MY BRAIN TOO, LOOK AGAIN LATER
newArr2 = np.diff(arr,n=2)

[  5 -30]


FINDING LCM

In [54]:
num1 = 4
num2 = 6
arr = np.array([3,6,9])
arr2 = np.arange(1,11)
# პოულობს უმცირეს საერთო ჯერადს, ამ შემთხვევაში დააბრუნებს 12-ს რადგან 12 არის უმცირესი რიცხვი რაც 6-ზეც იყოფა და 4-ზეც.
lcm = np.lcm(num1,num2)
# პოულობს უმცირეს საერთო ჯერადს მასივის ელემენტებს შორის.
lcmOfArrayNums = np.lcm.reduce(arr)
# პოულობს უმცირეს საერთო ჯერადს მასივის ელემენტებს შორის.
lcmOfArangeArrayNums = np.lcm.reduce(arr2)

2520


FINDING GCD

In [58]:
num1 = 6
num2 = 9
arr = np.array([15,10,20])
# პოულობს უდიდესს საერთო გამყოფს.
gcd = np.gcd(num1,num2)

# პოულობს უდიდესს საერთო გამყოფს მასივის ელემენტებს შორის.
gcdOfArrayNums = np.gcd.reduce(arr)

5
